/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.util.Map;

/**
 *
 * @author Aleksa
 */
public class FKasa extends javax.swing.JDialog {

    private Map<String,Integer> kasa;
    /**
     * Creates new form FKasa
     */
    public FKasa(java.awt.Frame parent, boolean modal,Map<String,Integer> kasa) {
        super(parent, modal);
        initComponents();
        this.kasa = kasa;
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txt100 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt50 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt20 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jbtnADD100 = new javax.swing.JButton();
        jbtnADD50 = new javax.swing.JButton();
        jbtnADD20 = new javax.swing.JButton();
        jbtnADD1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("100");

        txt100.setEditable(false);

        jLabel5.setText("50");

        txt50.setEditable(false);

        jLabel6.setText("20");

        txt20.setEditable(false);

        jLabel7.setText("1");

        txt1.setEditable(false);

        jbtnADD100.setText("ADD");
        jbtnADD100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnADD100ActionPerformed(evt);
            }
        });

        jbtnADD50.setText("ADD");
        jbtnADD50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnADD50ActionPerformed(evt);
            }
        });

        jbtnADD20.setText("ADD");
        jbtnADD20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnADD20ActionPerformed(evt);
            }
        });

        jbtnADD1.setText("ADD");
        jbtnADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnADD1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt100, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnADD100)
                    .addComponent(jbtnADD50)
                    .addComponent(jbtnADD20)
                    .addComponent(jbtnADD1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txt100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnADD100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnADD50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnADD20)
                            .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnADD1)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnADD100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnADD100ActionPerformed
        kasa.put("100", kasa.get("100") + 1);
        prepareKasa();
    }//GEN-LAST:event_jbtnADD100ActionPerformed

    private void jbtnADD50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnADD50ActionPerformed
         kasa.put("50", kasa.get("50") + 1);
        prepareKasa();
    }//GEN-LAST:event_jbtnADD50ActionPerformed

    private void jbtnADD20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnADD20ActionPerformed
         kasa.put("20", kasa.get("20") + 1);
        prepareKasa();
    }//GEN-LAST:event_jbtnADD20ActionPerformed

    private void jbtnADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnADD1ActionPerformed
         kasa.put("1", kasa.get("1") + 1);
        prepareKasa();
    }//GEN-LAST:event_jbtnADD1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtnADD1;
    private javax.swing.JButton jbtnADD100;
    private javax.swing.JButton jbtnADD20;
    private javax.swing.JButton jbtnADD50;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt100;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt50;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        prepareKasa();
    }

    private void prepareKasa() {
        txt100.setText(String.valueOf(kasa.get("100")));
        txt50.setText(String.valueOf(kasa.get("50")));
        txt20.setText(String.valueOf(kasa.get("20")));
        txt1.setText(String.valueOf(kasa.get("1")));
    }
}
